# Generated by Django 5.1.2 on 2024-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=2056)),
                ('blogger_name', models.CharField(max_length=200)),
                ('blogger_image', models.CharField(max_length=2083)),
                ('publish_time', models.IntegerField()),
            ],
        ),
    ]
